server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/IdeaProjects/msa/native-file-repo
        git:
          uri: https://github.com/YeaChan05/git-local-repo